//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 02:30:04 PM EST 
//


package org.bedework.schemas.licenses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Set of information about jars 
 *       
 * 
 * <p>Java class for JarLicensesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JarLicensesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jarLicense" type="{http://bedework.org/schemas/licenses}JarLicenseType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JarLicensesType", propOrder = {
    "jarLicense"
})
public class JarLicensesType {

    protected List<JarLicenseType> jarLicense;

    /**
     * Gets the value of the jarLicense property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jarLicense property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJarLicense().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JarLicenseType }
     * 
     * 
     */
    public List<JarLicenseType> getJarLicense() {
        if (jarLicense == null) {
            jarLicense = new ArrayList<JarLicenseType>();
        }
        return this.jarLicense;
    }

}
