//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 02:30:04 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bedework.org/schemas/licenses", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.bedework.schemas.licenses;
